name: SIL Tests & Pico Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "firmware/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "firmware/**"
      - ".github/workflows/**"
    

jobs:
  sil-tests:
    name: Run STM Checks & SIL tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get Submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive		
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Run tests on SIL
        run: |
          cd firmware
          pio test -e sil -vvv  no tests for this repo rn

      - name: Quality Check STM
        run: |
          cd firmware
         # pio check -e nucleo_f411re not working rn :(
 
  build-stm:
    name: Build STM Firmware
    runs-on: ubuntu-latest
    needs: sil-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build STM firmware f0
        run: |
          cd firmware
          pio run -e stm32f072c8t6

      - name: Build STM firmware f4
        run: |
          cd firmware
          pio run -e nucleo_f411re

      - name: Upload STM_F4 firmware
        uses: actions/upload-artifact@v4
        with:
          name: stmf4-firmware
          path: firmware/.pio/build/nucleo_f411re

      - name: Upload STM_F0 firmware
        uses: actions/upload-artifact@v4
        with:
          name: stmf0-firmware
          path: firmware/.pio/build/smt32f072c8t6
